"DOTAHeroes"
{
    //=================================================================================================================
	// HERO: Skywrath Mage
	//=================================================================================================================
	"npc_dota_hero_skywrath_mage_custom"
	{
		"override_hero"			"npc_dota_hero_skywrath_mage"
		"Ability1"				"skywrath_mage_arcane_bolt_custom"
		"Ability3"				"skywrath_mage_ancient_seal"
	}
}