"DOTAAbilities"
{
    "skywrath_mage_arcane_bolt_custom"
    {
        // General
        //-------------------------------------------------------------------------------------------------------------
        "BaseClass"                     "ability_lua"
        "AbilityTextureName"            "skywrath_mage_arcane_bolt"
        "ScriptFile"                    "abilities/skywrath_mage/skywrath_mage_arcane_bolt_custom.lua"
        "AbilityBehavior"               "DOTA_ABILITY_BEHAVIOR_UNIT_TARGET"
        "AbilityUnitTargetTeam"         "DOTA_UNIT_TARGET_TEAM_ENEMY"
        "AbilityUnitTargetType"         "DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
        "AbilityUnitDamageType"         "DAMAGE_TYPE_MAGICAL"
        "SpellImmunityType"             "SPELL_IMMUNITY_ENEMIES_NO"
        "FightRecapLevel"               "1"
        "AbilitySound"                  "Hero_SkywrathMage.ArcaneBolt.Cast"

        // Casting
        //-------------------------------------------------------------------------------------------------------------
        "AbilityCastRange"              "875"
        "AbilityCastPoint"              "0.1 0.1 0.1 0.1"

        // Time
        //-------------------------------------------------------------------------------------------------------------
        "AbilityCooldown"               "5.0 4.0 3.0 2.0"

        // Cost
        //-------------------------------------------------------------------------------------------------------------
        "AbilityManaCost"               "90"

        // Special
        //-------------------------------------------------------------------------------------------------------------
        "AbilityValues"
        {
        "bolt_speed"              "500"
        "bolt_vision_radius"      "325"
        "bolt_damage"             "60 80 100 120"
        "int_multiplier"
        {
            "value" "1.6"
            "CalculateSpellDamageTooltip" "1"
        }
        "vision_duration"         "3.34"
        }
        "AbilityCastAnimation"      "ACT_DOTA_CAST_ABILITY_1"
    }

    //=================================================================================================================
    // Skywrath Mage: Ancient Seal
    //=================================================================================================================
    "skywrath_mage_ancient_seal"
    {
        // General
        //-------------------------------------------------------------------------------------------------------------
        "BaseClass"                     "ability_lua"
        "AbilityTextureName"            "skywrath_mage_ancient_seal"
        "ScriptFile"                    "abilities/skywrath_mage/skywrath_mage_ancient_seal"
        "AbilityBehavior"               "DOTA_ABILITY_BEHAVIOR_UNIT_TARGET"
        "AbilityUnitTargetTeam"         "DOTA_UNIT_TARGET_TEAM_BOTH"
        "AbilityUnitTargetType"         "DOTA_UNIT_TARGET_HERO | DOTA_UNIT_TARGET_BASIC"
        "SpellImmunityType"             "SPELL_IMMUNITY_ENEMIES_NO"
        "SpellDispellableType"          "SPELL_DISPELLABLE_YES"
        "AbilitySound"                  "Hero_SkywrathMage.AncientSeal.Target"

        // Casting
        //-------------------------------------------------------------------------------------------------------------
        "AbilityCastRange"              "700 750 800 850"
        "AbilityCastPoint"              "0.1 0.1 0.1 0.1"

        // Time
        //-------------------------------------------------------------------------------------------------------------
        "AbilityCooldown"               "14"

        // Cost
        //-------------------------------------------------------------------------------------------------------------
        "AbilityManaCost"               "80 90 100 110"

        // Special
        //-------------------------------------------------------------------------------------------------------------
        "AbilityValues"
        {
        "resist_debuff"           "30 35 40 45"
        "seal_duration"           "30.0 40.0 50.0 60.0"
        }
        "AbilityCastAnimation"      "ACT_DOTA_CAST_ABILITY_3"
    }
}